import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen max-h-screen overflow-y-scroll overflow-x-hidden bg-slate-400 flex-col items-center p-4 justify-between text-black">
          {children}
        </main>
      </body>
    </html>
  );
}
